project_id = "zcgkygxcyuupexiyrvdz"

[functions.stripe-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.kakaopay-checkout]
verify_jwt = true

[functions.toss-checkout]
verify_jwt = true

[functions.paypal-checkout]
verify_jwt = true

[functions.subscription-status]
verify_jwt = true

[functions.enhanced-auth-emails]
verify_jwt = false

[functions.manage-users]
verify_jwt = true
