// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types_updated';

const SUPABASE_URL = "https://zcgkygxcyuupexiyrvdz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjZ2t5Z3hjeXV1cGV4aXlydmR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NjYwMDgsImV4cCI6MjA2OTM0MjAwOH0.YitOBBcjo_wc3V60EEqBzPImgz0w_fbidXvIWI8uMxk";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Missing Supabase environment variables');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});